on: [push, pull_request]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rsconnect"), type = "binary")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Push to shinyapps.io
        run: |
          rsconnect::setAccountInfo(name="${{secrets.SHINY_ACC_NAME}}", token="${{secrets.TOKEN}}", secret="${{secrets.SECRET}}")
          rsconnect::deployApp(appName = 'dinnR')
        shell: Rscript {0}